import Accordion from 'react-bootstrap/Accordion';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faMagnifyingGlass, faFileExport, faCheck, faExclamation,faArrowUpRightFromSquare,faArrowsRotate,faFilterCircleXmark,faListCheck,faRobot, faSignature} from '@fortawesome/free-solid-svg-icons'

function Instructions(){
    return (
        <Accordion defaultActiveKey="0">
            <Accordion.Item eventKey="0">
                <Accordion.Header><b>Instructions</b></Accordion.Header>
                    <Accordion.Body>
                        <ul>Status Guide
                            <li><FontAwesomeIcon icon={faExclamation} />&emsp;&emsp;LMT Info Needed: [ACTION REQUIRED] Navigate to the info tab of the transaction to identify fields missing, and enter those missing values in LMT</li>
                            <li><FontAwesomeIcon icon={faListCheck} />&emsp;Approval Needed: [ACTION REQUIRED] Navigate to the action panel within the info tab of the transaction to approve for bot processing</li>
                            <li><FontAwesomeIcon icon={faRobot} />&emsp;Awaiting Bot: COR/ACOR emails will be updated in LMT and a new COR/ACOR letter will be generated by the bot during its next run</li>
                            <li><FontAwesomeIcon icon={faSignature} />&emsp;Docusign Sent: Navigate to the info tab of the transaction to track COR/ACOR Letter Docusign signing status for all recipients</li>
                            <li><FontAwesomeIcon icon={faCheck} />&emsp;Completed: COR/ACOR letter, Agency letter and Lessor letter have been sent to respective parties and uploaded to GREX and LMT by the bot. No further action is required</li>
                        </ul>
                        <ul>Icon Guide
                            <li><FontAwesomeIcon icon={faArrowsRotate} />&emsp;Select this button to refresh dashboard data</li>
                            <li><FontAwesomeIcon icon={faFilterCircleXmark} />&emsp;Select this button to reset all filters to view all entries</li>
                            <li><FontAwesomeIcon icon={faArrowUpRightFromSquare} />&emsp;Select this button to submit a new COR/ACOR change request. This will take you to the COR/ACOR Change Form</li>
                            <li><FontAwesomeIcon icon={faFileExport} />&emsp;Select this button to export the visible rows of the table to a google sheet</li>
                            <li><FontAwesomeIcon icon={faMagnifyingGlass} />&emsp;Select this button to view more information regarding each entry and to take any actions</li>
                        </ul>
                    </Accordion.Body>
            </Accordion.Item>
        </Accordion>
    )
}

export default Instructions;